name: libmpv_dart
description: "A Flutter FFI plugin for libmpv that provides Dart bindings for libmpv."
version: 0.0.3
homepage: https://github.com/Playboy-Player/libmpv_dart

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  package_config: ^2.1.0
  path: ^1.9.0
  collection: ^1.15.0
  http: ^1.2.1
  archive: ^3.4.10

dev_dependencies:
  ffigen: ^9.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        # ffiPlugin: true
        pluginClass: LibmpvDartPlugin
executables:
  setup: setup
ffigen:
  name: LibMPV
  description: 'Dart binding for libmpv'
  output: 'lib/gen/bindings.dart'
  headers:
    entry-points:
      - 'src/mpv/client.h'